spring:
  application:
    name:
      WhatIfApp
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23licnWMRXuA9EAHfv
            client-secret: e7328bc344033a3e9b2559685aba90ce85df1482
            scope: profile,email
          google:
            client-id: 60618107051-ifle760f86rjs6b50c296htdtqk726o0.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/whatif_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect